name: build

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub'

jobs:
  build:

    runs-on: 'windows-2022'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    # - name: remove old vckpg
    #   run: rm -r -force $env:VCPKG_INSTALLATION_ROOT

    # - name: checkout vcpkg
    #   uses: actions/checkout@v3
    #   with:
    #     repository: 'microsoft/vcpkg'
    #     ref: '2022.10.19'
    #     path: ${{ env.VCPKG_INSTALLATION_ROOT }}

    # - name: setup vcpkg
    #   run: |
    #     ./bootstrap-vcpkg.bat
    #     $env:Path += ";" + $env:VCPKG_INSTALLATION_ROOT
    #   working-directory: ${{ env.VCPKG_INSTALLATION_ROOT }}

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: setup nuget
      run: nuget.exe sources add -source "https://nuget.pkg.github.com/WindowDetective/index.json"

    - name: setup gt5
      run: vcpkg install

    - name: vcpkg install
      run: ./vcpkg/vcpkg install --clean-buildtrees-after-build --clean-downloads-after-build

    - name: build
      run: msbuild "Window Detective.sln" /p:Configuration=Debug /p:Platform=Win32
