name: build

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub'

jobs:
  build:

    runs-on: 'windows-2022'

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: setup nuget
      run: |
        nuget.exe sources add `
          -source "https://nuget.pkg.github.com/WindowDetective/index.json" `
          -storepasswordincleartext `
          -name "GitHub" `
          -username "WindowDetective" `
          -password "${{ secrets.GITHUB_TOKEN }}"
        nuget.exe setapikey "${{ secrets.GITHUB_TOKEN }}" `
          -source "https://nuget.pkg.github.com/WindowDetective/index.json"
     
    - name: setup vcpkg
      uses: lukka/run-vcpkg@v11.5

    - name: vcpkg install
      run: ./vcpkg/vcpkg install --clean-buildtrees-after-build --clean-downloads-after-build

    - name: build
      run: msbuild "Window Detective.sln" /p:Configuration=Debug /p:Platform=Win32
